### PR TITLE
Added Merch-Designer

### PR DESCRIPTION
**Pull request by Abdulmumin1**
Merch-Designer is a website to build and create amazing merches blazing fast, it in early stages and i think the community can make this project great ✊.

### CODE REVIEW

**Comment by ykdojo** [comment]
Thank you, just checked it again.

I still feel like this project is too early and it doesn't have enough info on README.

What is this for exactly, anyway? Is it for your own merch store or are you making it for someone else?

**Comment by Abdulmumin1** [comment]
About the README, someone is  working on that, and the idea is, it for designing merches, for now only t-shirt merch only.
The idea is dump i know :disappointed: .
but you can design and render out cool merches on the [website](https://merch-designer-zeta.vercel.app) :point_down: 

merch(48)

merch(43)

merch(46)

**Comment by ykdojo** [comment]
Thank you. After designing the merch, is there a way for users to actually get it by getting it printed somewhere, though?

**Comment by Abdulmumin1** [comment]
> a way for users to actually get it by getting it printed somewhere, though?

nope, it has nothing to do with printing merches, only designing :smile:, isn't it cool :sunglasses:?

**Pull request closed without merging**
